### ISSUE TITLE
Remove upper-case for first sentence in posts.

### ISSUE THREAD

**Issue by farynaio** [kangabell/serena#9]
How to remove upper-case for first sentence in posts?

I found this behaviour on single-post page and home page.

**Comment by kangabell** [comment]
The uppercase is in the CSS with the following rule:
`.post:not(.sticky) .entry-content p:first-child::first-line {
    font-family: "Palatino Small Caps";
}`

You can override this by adding the following rule in your child theme, to change it back to the default font:
`.post:not(.sticky) .entry-content p:first-child::first-line {
    font-family: "Adobe Caslon Pro";
}`

**Comment by farynaio** [comment]
Thanks tip.

This one didn't take precedence before parent style, had to add content id selector at beginning:

```
#content .post:not(.sticky) .entry-content p:first-child::first-line {
  font-family: "Adobe Caslon Pro";
}
```
